[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt",
    "python manage.py collectstatic --noinput",
    "python manage.py migrate --noinput",
    "python manage.py migrate --database=goldbet_db --noinput",
    "python manage.py migrate --database=better_db --noinput",
    "python manage.py setup_agenzie --create-agenzie --create-users"
]

[start]
cmd = "gunicorn agenzia.wsgi --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info"