[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt",
    "python manage.py migrate --database=default",
    "python manage.py migrate --database=goldbet_db", 
    "python manage.py migrate --database=better_db",
    "python manage.py init_railway",
    "python manage.py load_railway_data",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn agenzia.wsgi --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info"