[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py wait_for_db && python manage.py migrate --verbosity=2 && python manage.py migrate --database=goldbet_db --verbosity=2 && python manage.py migrate --database=better_db --verbosity=2 && python manage.py migrate --database=planet_db --verbosity=2 && gunicorn agenzia.wsgi --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info"