[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn agenzia.wsgi --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"