# Generated by Django 5.2.1 on 2025-05-11 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fido_massimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.CharField(choices=[('A', 'Eccellente'), ('B', 'Buono'), ('C', 'Medio'), ('D', 'Rischio'), ('E', 'Alto Rischio')], default='C', max_length=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti_creati', to=settings.AUTH_USER_MODEL)),
                ('modificato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti_modificati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Comunicazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('avviso', 'Avviso'), ('sollecito', 'Sollecito'), ('informativa', 'Informativa')], max_length=12)),
                ('contenuto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('non_letta', 'Non Letta'), ('letta', 'Letta')], default='non_letta', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicazioni', to='app.cliente')),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicazioni_inviate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicazione',
                'verbose_name_plural': 'Comunicazioni',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='DistintaCassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('ora_inizio', models.TimeField(default=django.utils.timezone.now)),
                ('ora_fine', models.TimeField(blank=True, null=True)),
                ('cassa_iniziale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cassa_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totale_entrate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totale_uscite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totale_bevande', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_terminale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('differenza_cassa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stato', models.CharField(choices=[('aperta', 'Aperta'), ('chiusa', 'Chiusa'), ('verificata', 'Verificata')], default='aperta', max_length=10)),
                ('data_verifica', models.DateTimeField(blank=True, null=True)),
                ('note_verifica', models.TextField(blank=True, null=True)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distinte_create', to=settings.AUTH_USER_MODEL)),
                ('verificata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distinte_verificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distinta di Cassa',
                'verbose_name_plural': 'Distinte di Cassa',
                'ordering': ['-data', '-ora_inizio'],
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('schedina', 'Schedina'), ('ricarica', 'Ricarica'), ('prelievo', 'Prelievo')], max_length=10)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldato', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='app.cliente')),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_creati', to=settings.AUTH_USER_MODEL)),
                ('distinta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='app.distintacassa')),
                ('modificato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_modificati', to=settings.AUTH_USER_MODEL)),
                ('movimento_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimento_saldo', to='app.movimento')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimenti',
                'ordering': ['-data'],
            },
        ),
    ]
