# Generated by Django 5.2.1 on 2025-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='tipo',
            field=models.CharField(choices=[('schedina', 'Schedina'), ('ricarica', 'Ricarica'), ('prelievo', 'Prelievo'), ('incasso_credito', 'Incasso Credito'), ('pagamento_debito', 'Pagamento Debito')], max_length=20),
        ),
    ]
