# Generated by Django 5.2.1 on 2025-05-24 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movimento_note_alter_movimento_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BilancioPeriodico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_riferimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldo_totale', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_clienti', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_online', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_agenti', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_cassa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_banca', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_ricavi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_spese', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_prelievi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_versamenti', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_altro', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilanci_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bilancio Periodico',
                'verbose_name_plural': 'Bilanci Periodici',
                'ordering': ['-data_riferimento'],
            },
        ),
        migrations.CreateModel(
            name='ContoFinanziario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('cassa', 'Cassa'), ('banca', 'Conto Bancario'), ('online', 'Conto Online'), ('clienti', 'Crediti Clienti'), ('agenti', 'Crediti Agenti'), ('spese', 'Spese'), ('ricavi', 'Ricavi'), ('prelievi', 'Prelievi Soci'), ('versamenti', 'Versamenti Soci'), ('altro', 'Altro')], max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conti_creati', to=settings.AUTH_USER_MODEL)),
                ('modificato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conti_modificati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conto Finanziario',
                'verbose_name_plural': 'Conti Finanziari',
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
