# Generated by Django 5.2.1 on 2025-05-24 10:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bilancioperiodico_contofinanziario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contofinanziario',
            name='tipo',
            field=models.CharField(choices=[('cassa', 'Cassa'), ('banca', 'Conto Bancario'), ('online', 'Conto Online'), ('clienti', 'Crediti Clienti'), ('agenti', 'Saldo Agent'), ('spese', 'Spese'), ('ricavi', 'Ricavi'), ('prelievi', 'Prelievi Soci'), ('versamenti', 'Versamenti Soci'), ('altro', 'Altro')], max_length=20),
        ),
        migrations.CreateModel(
            name='MovimentoConti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('deposito', 'Deposito'), ('prelievo', 'Prelievo'), ('giroconto', 'Giroconto'), ('modifica', 'Modifica Diretta')], max_length=20)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_origine_pre', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo_origine_post', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo_destinazione_pre', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo_destinazione_post', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('conto_destinazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_entrata', to='app.contofinanziario')),
                ('conto_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_uscita', to='app.contofinanziario')),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_conti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento tra Conti',
                'verbose_name_plural': 'Movimenti tra Conti',
                'ordering': ['-data'],
            },
        ),
    ]
