# Generated by Django 5.2.4 on 2025-08-11 07:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_agenzia_profiloutente'),
    ]

    operations = [
        migrations.AddField(
            model_name='distintacassa',
            name='note_distinta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distintacassa',
            name='ora_inizio',
            field=models.TimeField(default=app.models.get_current_time),
        ),
    ]
