# Generated by Django migration for missing categoria and tassabile fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_distintacassa_note_distinta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contofinanziario',
            name='categoria',
            field=models.CharField(
                choices=[
                    ('liquidita', 'Liquidità'), 
                    ('crediti', 'Crediti'), 
                    ('debiti', 'Debiti'), 
                    ('ricavi', 'Ricavi'), 
                    ('costi', 'Costi Operativi'), 
                    ('imposte', 'Imposte e Tasse')
                ], 
                default='liquidita', 
                help_text='Categoria contabile per bilancio', 
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='contofinanziario',
            name='tassabile',
            field=models.BooleanField(
                default=True, 
                help_text='Concorre al calcolo delle imposte'
            ),
        ),
    ]