# Generated by Django 5.2.4 on 2025-09-02 08:37

import app.database_utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_categoria_tassabile_to_contofinanziario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlloQuadratura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_controllo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inizio_periodo', models.DateTimeField(help_text='Inizio periodo di controllo')),
                ('data_fine_periodo', models.DateTimeField(help_text='Fine periodo di controllo')),
                ('saldo_iniziale', models.DecimalField(decimal_places=2, help_text="Saldo all'inizio del periodo", max_digits=15)),
                ('saldo_finale_reale', models.DecimalField(decimal_places=2, help_text='Saldo effettivo rilevato', max_digits=15)),
                ('saldo_finale_calcolato', models.DecimalField(decimal_places=2, help_text='Saldo teorico da movimenti', max_digits=15)),
                ('differenza', models.DecimalField(decimal_places=2, editable=False, help_text='Ammanco/Surplus rilevato', max_digits=15)),
                ('totale_entrate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('totale_uscite', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('numero_movimenti', models.IntegerField(default=0)),
                ('controllo_generale', models.BooleanField(default=True, help_text='True se controllo generale, False se su conto specifico')),
                ('note_controllo', models.TextField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('in_corso', 'Controllo in Corso'), ('quadrato', 'Quadrato'), ('differenza', 'Con Differenze'), ('ammanco', 'Ammanco Rilevato')], default='in_corso', max_length=20)),
                ('conto_controllato', models.ForeignKey(blank=True, help_text='Conto specifico controllato', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.contofinanziario')),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlli_quadratura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controllo Quadratura',
                'verbose_name_plural': 'Controlli Quadratura',
                'ordering': ['-data_controllo'],
            },
            bases=(app.database_utils.MultiDatabaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimentoCassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_movimento', models.CharField(choices=[('apertura_distinta', 'Apertura Distinta'), ('chiusura_distinta', 'Chiusura Distinta'), ('verifica_distinta', 'Verifica Distinta'), ('giroconto_entrata', 'Giroconto in Entrata'), ('giroconto_uscita', 'Giroconto in Uscita'), ('deposito', 'Deposito Manuale'), ('prelievo', 'Prelievo Manuale'), ('correzione', 'Correzione Manuale'), ('inizializzazione', 'Inizializzazione Sistema')], max_length=30)),
                ('importo', models.DecimalField(decimal_places=2, help_text='Positivo per entrate, negativo per uscite', max_digits=15)),
                ('saldo_precedente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_nuovo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descrizione', models.TextField(help_text='Descrizione dettagliata del movimento')),
                ('distinta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_cassa', to='app.distintacassa')),
                ('movimento_conti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_cassa', to='app.movimentoconti')),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_cassa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento Cassa',
                'verbose_name_plural': 'Movimenti Cassa',
                'ordering': ['-data_movimento'],
            },
            bases=(app.database_utils.MultiDatabaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SnapshotSaldoCassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_snapshot', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldo_precedente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_nuovo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('differenza', models.DecimalField(decimal_places=2, max_digits=15)),
                ('causale', models.CharField(help_text='Motivo della variazione', max_length=100)),
                ('riferimento_id', models.PositiveIntegerField(blank=True, help_text='ID del record correlato (distinta, movimento, etc.)', null=True)),
                ('riferimento_tipo', models.CharField(blank=True, help_text='Tipo di record correlato', max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_cassa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot Saldo Cassa',
                'verbose_name_plural': 'Snapshots Saldo Cassa',
                'ordering': ['-data_snapshot'],
            },
            bases=(app.database_utils.MultiDatabaseMixin, models.Model),
        ),
    ]
