# Generated by Django 5.2.4 on 2026-02-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_controlloquadratura_movimentocassa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='saldo_progressivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo totale di tutti i clienti dopo questo movimento', max_digits=10, null=True),
        ),
    ]
