# Generated by Django 5.2.4 on 2026-02-14 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_movimento_saldo_progressivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiepilogoGiornaliero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data del riepilogo', unique=True)),
                ('saldo_crediti', models.DecimalField(decimal_places=2, default=0, help_text='Saldo dell\'ultimo movimento crediti clienti della giornata', max_digits=10)),
                ('saldo_cassa', models.DecimalField(decimal_places=2, default=0, help_text='Saldo finale dell\'ultima distinta della giornata', max_digits=10)),
                ('cassa_2', models.DecimalField(decimal_places=2, default=0, help_text='Somma del totale bevande delle distinte della giornata', max_digits=10)),
                ('differenza_distinta', models.DecimalField(decimal_places=2, default=0, help_text='Somma della differenza distinta delle distinte della giornata', max_digits=10)),
                ('saldo_ced', models.DecimalField(decimal_places=2, default=0, help_text='Saldo CED', max_digits=10)),
                ('saldo_pvonline', models.DecimalField(decimal_places=2, default=0, help_text='Saldo PV Online', max_digits=10)),
                ('giroconto_ced', models.DecimalField(decimal_places=2, default=0, help_text='Giroconto CED', max_digits=10)),
                ('giroconto_online', models.DecimalField(decimal_places=2, default=0, help_text='Giroconto Online', max_digits=10)),
                ('sovvenzione', models.DecimalField(decimal_places=2, default=0, help_text='Sovvenzione', max_digits=10)),
                ('restituzione', models.DecimalField(decimal_places=2, default=0, help_text='Restituzione', max_digits=10)),
                ('totale', models.DecimalField(decimal_places=2, default=0, help_text='Totale calcolato', max_digits=10)),
                ('saldo_progressivo', models.DecimalField(decimal_places=2, default=0, help_text='Saldo progressivo', max_digits=10)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riepiloghi_creati', to=settings.AUTH_USER_MODEL)),
                ('modificato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riepiloghi_modificati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riepilogo Giornaliero',
                'verbose_name_plural': 'Riepiloghi Giornalieri',
                'ordering': ['-data'],
            },
        ),
    ]
