# Generated by Django 4.2.29 on 2026-06-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_riepilogogiornaliero'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenzia',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Chat/gruppo Telegram a cui inviare le notifiche di questa agenzia (es. -1001234567890)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contofinanziario',
            name='notifica_telegram',
            field=models.BooleanField(default=False, help_text='Invia una notifica Telegram per ogni movimento di questo conto'),
        ),
    ]
