# Generated by Django 4.2.29 on 2026-06-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_agenzia_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='notifica_movimenti',
            field=models.BooleanField(default=False, help_text='Invia una notifica Telegram per ogni movimento di questo cliente (anche senza superamento del fido)'),
        ),
    ]
