# Generated by Django 4.2.29 on 2026-06-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cliente_notifica_movimenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenzia',
            name='soglia_cassa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se la cassa finale di una distinta supera questo valore, invia un alert Telegram. Vuoto = nessun alert.', max_digits=12, null=True),
        ),
    ]
