# Generated by Django 4.2.29 on 2026-08-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_agenzia_soglia_cassa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoEsterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cast_agent', 'CAST Agent (Goldbet/Lottomatica)')], default='cast_agent', max_length=30)),
                ('data', models.DateField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rilevato_il', models.DateTimeField(auto_now=True)),
                ('agenzia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldi_esterni', to='app.agenzia')),
            ],
            options={
                'verbose_name': 'Saldo Esterno',
                'verbose_name_plural': 'Saldi Esterni',
                'ordering': ['-data'],
                'unique_together': {('agenzia', 'tipo', 'data')},
            },
        ),
    ]
