# Generated by Django 4.2.29 on 2026-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_saldoesterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoesterno',
            name='tipo',
            field=models.CharField(choices=[('cast_agent', 'Saldo CAST'), ('giroconto_online', 'Giroconto Online'), ('giroconto_terrestre', 'Giroconto Terrestre'), ('saldo_online', 'Saldo Online'), ('prelievi', 'Prelievi'), ('versamenti', 'Versamenti')], default='cast_agent', max_length=30),
        ),
    ]
