# Generated by Django 4.2.29 on 2026-08-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_saldoesterno_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='conto_servizio',
            field=models.BooleanField(default=False, help_text='Conto di servizio (POS, spese, aggiustamenti cassa): escluso dai totali crediti clienti'),
        ),
    ]
