# Generated by Django 4.2.29 on 2026-08-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_cliente_conto_servizio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoesterno',
            name='tipo',
            field=models.CharField(choices=[('cast_agent', 'Saldo CED'), ('giroconto_online', 'Giroconto Online'), ('giroconto_terrestre', 'Giroconto Terrestre'), ('saldo_online', 'Saldo Online'), ('prelievi', 'Prelievi'), ('versamenti', 'Versamenti'), ('altro', 'Altro'), ('giroconto_conti_servizio', 'Giroconto Conti di Servizio')], default='cast_agent', max_length=30),
        ),
    ]
