# Generated by Django 4.2.29 on 2026-08-26 07:37

import app.database_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_alter_saldoesterno_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzzeramentoProgrammato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimento_ids', models.TextField(help_text='ID dei movimenti selezionati, separati da virgola')),
                ('data_richiesta', models.DateTimeField(default=django.utils.timezone.now)),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('in_esecuzione', 'In esecuzione'), ('eseguito', 'Eseguito'), ('annullato', 'Annullato'), ('errore', 'Errore')], default='in_attesa', max_length=15)),
                ('data_esecuzione', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='azzeramenti_programmati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Azzeramento Programmato',
                'verbose_name_plural': 'Azzeramenti Programmati',
                'ordering': ['-data_richiesta'],
            },
            bases=(app.database_utils.MultiDatabaseMixin, models.Model),
        ),
    ]
