# Generated by Django 4.2.29 on 2026-08-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_azzeramentoprogrammato'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenzia',
            name='cast_account_id',
            field=models.CharField(blank=True, default='', help_text='ID conto CAST associato a questa agenzia. Viene impostato automaticamente alla prima estrazione; le estrazioni con un conto CAST diverso vengono rifiutate. Svuota il campo per riassociarlo.', max_length=100),
        ),
    ]
