# Generated by Django 4.2.29 on 2026-09-02 16:23

import app.database_utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_agenzia_cast_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.SlugField(help_text='Codice stabile usato per aggregare tra agenzie', max_length=40, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
                ('deducibile', models.BooleanField(default=True, help_text='Concorre alla stima delle imposte')),
            ],
            options={
                'verbose_name': 'Categoria di Spesa',
                'verbose_name_plural': 'Categorie di Spesa',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContoEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField()),
                ('mese', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('chiuso', 'Chiuso')], default='bozza', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conti_economici_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conto Economico',
                'verbose_name_plural': 'Conti Economici',
                'ordering': ['-anno', '-mese'],
                'unique_together': {('anno', 'mese')},
            },
            bases=(app.database_utils.MultiDatabaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProdottoRicavo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.SlugField(help_text='Codice stabile usato per aggregare tra agenzie', max_length=40, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prodotto (Ricavi)',
                'verbose_name_plural': 'Prodotti (Ricavi)',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='VoceRicavo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodotto_codice', models.SlugField(blank=True, help_text='Codice ProdottoRicavo (vuoto = voce manuale)', max_length=40, null=True)),
                ('descrizione', models.CharField(blank=True, default='', max_length=200)),
                ('importo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fonte', models.CharField(choices=[('manuale', 'Manuale'), ('cast', 'Cast')], default='manuale', max_length=10)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('conto_economico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci_ricavo', to='app.contoeconomico')),
            ],
            options={
                'verbose_name': 'Voce di Ricavo',
                'verbose_name_plural': 'Voci di Ricavo',
                'ordering': ['id'],
            },
            bases=(app.database_utils.MultiDatabaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VoceCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_codice', models.SlugField(blank=True, help_text='Codice CategoriaSpesa (vuoto = da classificare)', max_length=40, null=True)),
                ('descrizione', models.CharField(blank=True, default='', max_length=200)),
                ('importo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data', models.DateField(blank=True, null=True)),
                ('fonte', models.CharField(choices=[('manuale', 'Manuale'), ('csv', 'Estratto conto'), ('conto_spese', 'Conto spese')], default='manuale', max_length=12)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('conto_economico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci_costo', to='app.contoeconomico')),
                ('movimento', models.ForeignKey(blank=True, help_text='Movimento conto-spese di origine (per dedup)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voci_costo', to='app.movimento')),
            ],
            options={
                'verbose_name': 'Voce di Costo',
                'verbose_name_plural': 'Voci di Costo',
                'ordering': ['id'],
            },
            bases=(app.database_utils.MultiDatabaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimentoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('descrizione', models.CharField(blank=True, default='', max_length=300)),
                ('importo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hash_riga', models.CharField(db_index=True, max_length=40)),
                ('categoria_codice', models.SlugField(blank=True, max_length=40, null=True)),
                ('stato', models.CharField(choices=[('da_classificare', 'Da classificare'), ('classificato', 'Classificato'), ('ignorato', 'Ignorato')], default='da_classificare', max_length=16)),
                ('file_nome', models.CharField(blank=True, default='', max_length=200)),
                ('importato_il', models.DateTimeField(auto_now_add=True)),
                ('conto_economico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe_bancarie', to='app.contoeconomico')),
                ('voce_costo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riga_bancaria', to='app.vocecosto')),
            ],
            options={
                'verbose_name': 'Movimento Bancario',
                'verbose_name_plural': 'Movimenti Bancari',
                'ordering': ['data', 'id'],
                'unique_together': {('conto_economico', 'hash_riga')},
            },
            bases=(app.database_utils.MultiDatabaseMixin, models.Model),
        ),
    ]
