# Generated by Django 4.2.29 on 2026-09-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_categoriaspesa_contoeconomico_prodottoricavo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentobancario',
            name='allocazioni',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vocecosto',
            name='origine_db',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='vocecosto',
            name='origine_mb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
