# Generated by Django 4.2.29 on 2026-09-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_movimentobancario_allocazioni_vocecosto_origine_db_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentobancario',
            name='prodotto_codice',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='vocericavo',
            name='origine_db',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='vocericavo',
            name='origine_mb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocericavo',
            name='fonte',
            field=models.CharField(choices=[('manuale', 'Manuale'), ('cast', 'Cast'), ('csv', 'Estratto conto')], default='manuale', max_length=10),
        ),
    ]
