# Generated by Django 4.2.29 on 2026-09-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_movimentobancario_prodotto_codice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria Prodotto',
                'verbose_name_plural': 'Categorie Prodotto',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='prodottoricavo',
            name='categoria_codice',
            field=models.SlugField(blank=True, help_text='Categoria prodotto (raggruppamento)', max_length=40, null=True),
        ),
    ]
