# Generated by Django 4.2.29 on 2026-09-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_categoriaprodotto_prodottoricavo_categoria_codice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria Costo',
                'verbose_name_plural': 'Categorie Costo',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='categoriaspesa',
            name='categoria_costo_codice',
            field=models.SlugField(blank=True, help_text='Macro-categoria costo (raggruppamento)', max_length=40, null=True),
        ),
    ]
