# Generated by Django 4.2.29 on 2026-09-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_escludi_movimenti_bancari_esistenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nascosto',
            field=models.BooleanField(default=False, help_text='Nascondi dalla lista clienti: gli operatori non lo vedono più (gestibile da Django admin)'),
        ),
    ]
