# Generated by Django 4.2.29 on 2026-09-17 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0031_gruppo_conto_economico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='conto_giroconto',
            field=models.BooleanField(default=False, help_text="Conto di giroconto inter-agenzia: un movimento su questo conto genera una richiesta da accettare presso l'agenzia partner (gestibile da Django admin)"),
        ),
        migrations.AddField(
            model_name='cliente',
            name='giroconto_agenzia',
            field=models.CharField(blank=True, default='', help_text="Nome dell'agenzia partner per il giroconto (es. 'Better'). Il movimento verrà registrato anche in quell'agenzia con segno opposto dopo l'accettazione.", max_length=100),
        ),
        migrations.CreateModel(
            name='RichiestaGiroconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conto_origine_id', models.IntegerField(help_text='pk del Cliente (conto giroconto) nel DB origine')),
                ('conto_origine_nome', models.CharField(blank=True, default='', max_length=200)),
                ('distinta_origine_id', models.IntegerField(help_text="pk della DistintaCassa aperta d'origine, catturata alla creazione")),
                ('tipo', models.CharField(choices=[('schedina', 'Schedina'), ('ricarica', 'Ricarica'), ('prelievo', 'Prelievo'), ('incasso_credito', 'Incasso Credito'), ('pagamento_debito', 'Pagamento Debito')], max_length=20)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, default='')),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('accettato', 'Accettato'), ('rifiutato', 'Rifiutato'), ('annullato', 'Annullato')], default='in_attesa', max_length=12)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_risposta', models.DateTimeField(blank=True, null=True)),
                ('note_risposta', models.TextField(blank=True, default='')),
                ('movimento_origine_id', models.IntegerField(blank=True, null=True)),
                ('movimento_dest_id', models.IntegerField(blank=True, null=True)),
                ('conto_dest_id', models.IntegerField(blank=True, null=True)),
                ('agenzia_destinazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giroconti_ricevuti', to='app.agenzia')),
                ('agenzia_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giroconti_inviati', to='app.agenzia')),
                ('operatore_origine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giroconti_creati', to=settings.AUTH_USER_MODEL)),
                ('operatore_risposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giroconti_risposti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Richiesta di Giroconto',
                'verbose_name_plural': 'Richieste di Giroconto',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
