# Generated by Django 4.2.29 on 2026-09-17 18:15

import app.database_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0032_cliente_conto_giroconto_cliente_giroconto_agenzia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ordine', models.IntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria Task',
                'verbose_name_plural': 'Categorie Task',
                'ordering': ['ordine', 'nome'],
            },
            bases=(app.database_utils.MultiDatabaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskAgenzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('priorita', models.CharField(choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=6)),
                ('stato', models.CharField(choices=[('da_fare', 'Da fare'), ('in_corso', 'In corso'), ('completata', 'Completata'), ('annullata', 'Annullata')], default='da_fare', max_length=12)),
                ('scadenza', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', help_text="Aggiornamenti (es. stato della segnalazione all'assistenza)")),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('data_completamento', models.DateTimeField(blank=True, null=True)),
                ('assegnato_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assegnate', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='app.categoriatask')),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_create', to=settings.AUTH_USER_MODEL)),
                ('modificato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_modificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task di Agenzia',
                'verbose_name_plural': 'Task di Agenzia',
                'ordering': ['data_creazione'],
            },
            bases=(app.database_utils.MultiDatabaseMixin, models.Model),
        ),
    ]
