# Generated by Django 4.2.29 on 2026-09-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_seed_categorie_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubblicitaLedwall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, default='', help_text="Solo per riconoscerla nell'elenco (non mostrato sul ledwall)", max_length=120)),
                ('dati', models.BinaryField(help_text="Contenuto dell'immagine")),
                ('content_type', models.CharField(default='image/png', max_length=60)),
                ('attivo', models.BooleanField(default=True, help_text='Se spento, non compare sul ledwall')),
                ('ordine', models.IntegerField(default=0, help_text="Ordine di rotazione (numero piu' basso prima)")),
                ('data_caricamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ledwall - Pubblicità',
                'verbose_name_plural': 'Ledwall - Pubblicità',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
