# Generated by Django 4.2.29 on 2026-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_pubblicitaledwall'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniLedwall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondi_scheda', models.FloatField(default=5, help_text='Secondi di permanenza di ogni scheda partita')),
                ('ogni_n_schede', models.IntegerField(default=4, help_text='Mostra la pubblicità ogni N schede partita')),
                ('secondi_pubblicita', models.FloatField(default=5, help_text='Secondi di default per ogni immagine pubblicitaria (usato se la singola immagine ha secondi = 0)')),
            ],
            options={
                'verbose_name': 'Ledwall - Impostazioni',
                'verbose_name_plural': 'Ledwall - Impostazioni',
            },
        ),
        migrations.AddField(
            model_name='pubblicitaledwall',
            name='secondi',
            field=models.FloatField(default=0, help_text='Secondi di permanenza di questa immagine (0 = usa il default globale)'),
        ),
        migrations.AddField(
            model_name='pubblicitaledwall',
            name='transizione',
            field=models.CharField(choices=[('destra', 'Scorrimento da destra'), ('zoom', 'Zoom'), ('alto', 'Dal basso'), ('dissolvenza', 'Dissolvenza')], default='destra', help_text='Effetto di entrata di questa immagine', max_length=12),
        ),
    ]
