# Generated by Django 4.2.29 on 2026-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_impostazioniledwall_pubblicitaledwall_secondi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetizioneLedwall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('short_name', models.CharField(help_text='Etichetta gialla sul ledwall (es. SERIE A)', max_length=20)),
                ('ordine', models.IntegerField(default=0, help_text='Priorità: numero più basso = più in alto')),
                ('attivo', models.BooleanField(default=True, help_text='Se spento, non compare sul ledwall')),
                ('aliases', models.TextField(blank=True, default='', help_text="Nomi esatti di diretta.it, uno per riga (es. 'ITALIA: Serie A')")),
                ('contiene', models.CharField(blank=True, default='', help_text="In alternativa: sottostringa del nome (es. 'champions league')", max_length=80)),
            ],
            options={
                'verbose_name': 'Ledwall - Competizione',
                'verbose_name_plural': 'Ledwall - Competizioni',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='impostazioniledwall',
            name='mostra_domani',
            field=models.BooleanField(default=False, help_text='Mostra anche le partite in programma domani (con la data)'),
        ),
        migrations.AddField(
            model_name='impostazioniledwall',
            name='mostra_live',
            field=models.BooleanField(default=True, help_text='Mostra le partite in corso (risultati live)'),
        ),
        migrations.AddField(
            model_name='impostazioniledwall',
            name='mostra_oggi_finite',
            field=models.BooleanField(default=True, help_text='Mostra i risultati finali delle partite di oggi'),
        ),
        migrations.AddField(
            model_name='impostazioniledwall',
            name='mostra_oggi_in_programma',
            field=models.BooleanField(default=True, help_text='Mostra le partite di oggi non ancora iniziate (orario)'),
        ),
    ]
