# Generated by Django 4.2.29 on 2026-09-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_seed_competizioni_ledwall'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioniledwall',
            name='secondi_barra_risultati',
            field=models.FloatField(default=24, help_text='Velocità barra risultati: secondi per un giro completo. Più basso = più veloce (es. 16 veloce, 40 lento)'),
        ),
    ]
