# Generated by Django 4.2.29 on 2026-09-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_impostazioniledwall_secondi_barra_risultati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impostazioniledwall',
            name='secondi_barra_risultati',
            field=models.FloatField(default=24, help_text='Velocità della barra risultati (costante, indipendente dal numero di partite). Più basso = più veloce. Default 24 (es. 16 veloce, 40 lento)'),
        ),
    ]
