# Generated by Django 4.2.29 on 2026-09-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_impostazioniledwall_secondi_barra_risultati'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioniledwall',
            name='loghi_hd',
            field=models.BooleanField(default=True, help_text='Loghi HD (API-Football) per le squadre principali; per le altre usa i loghi di diretta.it'),
        ),
    ]
